//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.PartnerProduct = new HashSet<PartnerProduct>();
        }
    
        public int IDPartner { get; set; }
        public int IDTypePartner { get; set; }
        public string NamePartner { get; set; }
        public string LastNamePartner { get; set; }
        public string FirstNamePartner { get; set; }
        public string PatronymicPartner { get; set; }
        public string EmailParnter { get; set; }
        public string NumberPartner { get; set; }
        public string AdressePartner { get; set; }
        public string INNPartner { get; set; }
        public int TopPartner { get; set; }
    
        public virtual PartnerType PartnerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
    }
}
